### ISSUE TITLE
更新引起的系统崩溃

### ISSUE THREAD

**Issue by newrookie001** [okxlin/docker-1panel#10]
docker compose部署了1panel
1、点击1panel页面右下角的更新，提示正在升级中（具体表述忘记了），等了很久刷新页面还是升级中。然后NAS就报错了，提示存储空间不足，需要检查RAMDisk。应该是1panel的下载路径/更新路径错误，直接将文件下载到了RAMdisk引起的这个问题。但如何修改为正确路径还不知道。
2、在具体容器界面，可以查看容器日志，但选择“清空”，就又报错了，提示“no such file or directory”。
![docker compose](https://github.com/okxlin/docker-1panel/assets/166485646/a99f52d8-54c7-4e98-8df8-61e00e4d5e35)
![RAMdisk故障](https://github.com/okxlin/docker-1panel/assets/166485646/30ae6403-fdb5-4757-8c64-f370ba4865d1)
![Uploading 删除日志错误.png…]()

**Comment by okxlin** [comment]
清理一下看看，

实际docker版运行的不推荐直接点击面板右下角更新，没效果的，也不推荐，因为重建镜像就会被恢复。

推荐拉取新镜像来实现更新的目的。

追求最新版本的话可以部署`latest`标签的版本，然后搭配应用商店里的`watchtower`应用实现自动更新。

**Comment by okxlin** [comment]
你重新部署一下吧，我稍后加个不要点击右下角更新的说明😂

**Comment by okxlin** [comment]
不过`Debian`下以前试过点击更新，倒是没有发现所说的问题来着

**Comment by okxlin** [comment]
## docker socket和存储卷路径一般不需要变动，Linux下默认路径一般不会变，

具体看不同系统，而改动，其他更多存储映射随意。
```
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /opt:/opt  # 文件存储映射
      - /root:/root  # 可选的文件存储映射
```

## 不需要升级容器内的1Panel程序，应该拉取新的1Panel镜像而升级。

```
docker stop 1panel && docker rm 1panel && \
docker pull moelin/1panel:latest && \
docker run -d \
    --name 1panel \
    --restart always \
    --network host \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /var/lib/docker/volumes:/var/lib/docker/volumes \
    -v /opt:/opt \
    -v /root:/root \
    -e TZ=Asia/Shanghai \
    moelin/1panel:latest
```

## 简单省心如之前所说直接上`watchtower`自动更新即可
