### ISSUE TITLE
群晖6.2.3安装后正常启动，无法登录，终端机1pctl user-info命令无法使用

### ISSUE THREAD

**Issue by ZGCdeGithub** [okxlin/docker-1panel#11]
群晖6.2.3安装后正常启用，且后台登录页面能打开，点击登录失败，登录接口返回500错误，无错误信息，docker日志无错误日志，终端机进入查看1pancel日志，发下如下错误
![image](https://github.com/okxlin/docker-1panel/assets/24607273/49a4e1fa-b588-4832-ae5a-7c4308609ab0)
使用1pctl user-info命令，出现如下错误
![image](https://github.com/okxlin/docker-1panel/assets/24607273/520e20fd-b5c1-4e00-a6b6-aa2aaf179d76)

**Comment by okxlin** [comment]
没有群晖机子，确实也不是很清楚，正常容器运行了不会这样。

`/opt`存储路径映射是不是有改动？这个不能改，并且如果这个宿主机没有文件夹的话可以手动创建一下，不太清楚群晖的权限级别。

然后删除容器，重新部署一下看看

![image](https://github.com/okxlin/docker-1panel/assets/61420215/e47d3c45-ce23-48ea-b686-eee68a19d9a3)

**Comment by ZGCdeGithub** [comment]
确实是/opt映射路径的问题，不能映射到群晖的共享文件夹中。谢谢了
