### ISSUE TITLE
[Discussion] 如何接管宿主机的SSH服务?

### ISSUE THREAD

**Issue by zuilintan** [okxlin/docker-1panel#12]
以绿联云DX4600为例, 
其SSH每三天会自动关闭, 
是否可以接管其SSH在面板端手动开启?

**Comment by okxlin** [comment]
这个建议在相关的社区、搜索引擎查找长时间开放SSH的办法，我没有持有这个，还真不知道。

如果只是自动关闭端口外部访问的，而不是关闭ssh服务功能的，或许还可以在1Panel面板的终端里添加宿主机IP端口进行连接。
