### ISSUE TITLE
安装内置应用异常

### ISSUE THREAD

**Issue by whkwkxsyf1991** [okxlin/docker-1panel#14]
大佬您好，目前遇到这样的问题，通过内置的应用商店直接安装应用会异常，因为相当于目录直接映射到宿主机的/opt下了，而不是我自己设置的/xxxx:/opt，每次安装需要手动编辑docker compose文件，将相对路径改成宿主机的绝对路径才能安装成功，有办法修改内置默认的opt目录吗

**Comment by okxlin** [comment]
仓库编译的默认要求宿主机路径要在/opt下，可能软链接方式说不定也行

***

修改内部的默认应用数据目录，需要重新编译镜像。

可以fork仓库分支后，修改

- install.override.sh
的`PANEL_BASE_DIR=/opt`

以及

- update_app_version.sh
里的相关路径

编译镜像后，使用自己的镜像

**Comment by whkwkxsyf1991** [comment]
好的，多谢大佬回复
