### ISSUE TITLE
可以运行，无法安装应用

### ISSUE THREAD

**Issue by bottleink404** [okxlin/docker-1panel#15]
大佬们有没有在nas上安装过，我直接在nas（几个品牌都试过了）的docker里进行安装，然后是可以访问的，但是无法下载应用
![image](https://github.com/user-attachments/assets/755eda5b-0cc3-4512-8b41-dd663d251149)
![image](https://github.com/user-attachments/assets/9e0b17fc-4271-46f8-a7a2-8187a92d1945)

安装的时候就会提示我“默认容器网络创建失败！Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?”

**Comment by okxlin** [comment]
- 不可调整参数
  - `/var/run/docker.sock`的相关映射

这个是调用docker功能用的，你修改了，调用不了接口自然用不了

**Comment by bottleink404** [comment]
那我应该前后映射都是这个不可调参数吗

**Comment by okxlin** [comment]
一般docker接口的映射，默认是`/var/run/docker.sock:/var/run/docker.sock`就行了，Linux系统下路径基本都是这个

**Comment by gitlsl** [comment]
````
(HTTP code 400) unexpected - failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/opt/1panel/apps/openresty/openresty/conf/mime.types" to rootfs at "/usr/local/openresty/nginx/conf/mime.types": mount /opt/1panel/apps/openresty/openresty/conf/mime.types:/usr/local/openresty/nginx/conf/mime.types (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
````


docker run -d  -p 10086:10086  --restart always  -v /var/lib/docker/volumes:/var/lib/docker/volumes -v /var/run/docker.sock:/var/run/docker.sock -v /e/dockerdata/1panel/opt:/opt -v /e/dockerdata/1panel/root:/root -e TZ=Asia/Shanghai   --name 1panel   moelin/1panel:latest

我在windows的控制中 执行上面命令 报上面的错误, 这个应该怎么改呢,  还是他只能在 linux的命令行下运行
