### ISSUE TITLE
拉取php环境报错

### ISSUE THREAD

**Issue by guidocn** [okxlin/docker-1panel#4]
![PixPin_2023-11-30_11-30-06](https://github.com/okxlin/docker-1panel/assets/75555539/3f2e3c54-97dd-4b2d-b780-3ada5a48ff72)

**Comment by okxlin** [comment]
你是改映射路径了？

`/opt:/opt`不要动，不然容易出问题

我这里是正常的
![image](https://github.com/okxlin/docker-1panel/assets/61420215/a98791ec-7df1-4d37-9e7b-11f50692ab5a)
