### ISSUE TITLE
大佬这种方式部署的能看到本地文件目录吗，我的好像读取不到/mnt下面的目录，所以不能使用他的定时备份本地目录文件

### ISSUE THREAD

**Issue by AlanWang2333** [okxlin/docker-1panel#5]
大佬，感谢你做的仓库，我的iStoreOS才能用上。
特别喜欢的商店，应用很多。我用x86的j3160的docker部署的
但是进1panel， 主机-文件，里面的很多文件目录不显示，
![1panel 主机-文件](https://github.com/okxlin/docker-1panel/assets/58912611/8cad7ab3-ecf4-4d61-a270-2e55bc2997e8)
比如最常用的/mnt目录，下面是空的
![mnt目录](https://github.com/okxlin/docker-1panel/assets/58912611/b9c9ff6d-8032-4484-a891-b1936222ae73)
这就导致备份：某个本地文件目录时出错，因为读取不到储存。
因为他的备份看起来挺好用的，可以每天凌晨备份docker，希望大佬看到帮帮我

**Comment by okxlin** [comment]
docker的存储映射添加就好了，

需要哪个目录就添加哪个目录映射

宿主机/mnt也一样，映射到容器内部里就好

-v /mnt:/mnt

可以看说明里的例子

https://hub.docker.com/r/moelin/1panel

**Comment by AlanWang2333** [comment]
> docker的存储映射添加就好了，
> 
> 需要哪个目录就添加哪个目录映射
> 
> 宿主机/mnt也一样，映射到容器内部里就好
> 
> -v /mnt:/mnt
> 
> 可以看说明里的例子
> 
> https://hub.docker.com/r/moelin/1panel

原来是这样😊映射目录之后，在/opt里面，竟然都有，感谢，感谢
