### ISSUE TITLE
只能本地访问，无法从局域网访问

### ISSUE THREAD

**Issue by boxhz** [okxlin/docker-1panel#6]
通过README中docker方式安装，只能从本地ip访问
![图片](https://github.com/okxlin/docker-1panel/assets/92076022/f4be2f30-4bd5-4882-ad58-80644979735c)
只能通过图中172开头的本地ip访问
电脑与服务器处于同一网络下，192IP局域网无法访问
![图片](https://github.com/okxlin/docker-1panel/assets/92076022/6f356ad3-ab83-413c-9f9b-ceb4977181c2)

**Comment by okxlin** [comment]
实际可能是运行的虚拟机/宿主机系统的防火墙问题，应该与1panel 容器软件无关。

本机能够访问表明docker运行的1panel端口监听即是正常。

或可以手动再放行一下防火墙端口
