### ISSUE TITLE
docker-compose.yml: `version` is obsolete

### ISSUE THREAD

**Issue by zfowed** [okxlin/docker-1panel#8]
安装应用会报错 `version` is obsolete

<img width="1313" alt="image" src="https://github.com/okxlin/docker-1panel/assets/23629388/f3b6a137-dc7c-4dba-bf2e-6ffef10cb9c8">

**Comment by okxlin** [comment]
应该与docker版本的1panel无关，

有试过一次就成功的，也有提示异常的，但重建一下应用就好了

![image](https://github.com/okxlin/docker-1panel/assets/61420215/a4936de7-a09c-445f-b69b-7868d7531230)

**Comment by okxlin** [comment]
新版docker-compose的特性，不需要定义服务版本了，不过目前看起来docker-compose.yml写了好像也没影响
